---
config:
  layout: elk
---
erDiagram
    contracts {
        INTEGER id PK 
        INTEGER network_id FK 
        INTEGER type FK 
    }

    networks {
        INTEGER id PK 
        INTEGER language FK 
        INTEGER publisher__identifier__scheme FK 
    }

    nodes {
        INTEGER id PK 
        INTEGER network_id FK 
    }

    organisations {
        INTEGER id PK 
        INTEGER identifier__scheme FK 
        INTEGER network_id FK 
    }

    phases {
        INTEGER id PK 
        INTEGER network_id FK 
    }

    relation_contracts_relatedPhases {
        INTEGER base_id PK,FK 
        INTEGER related_id PK,FK 
    }

    relation_nodes_networkProviders {
        INTEGER base_id PK,FK 
        INTEGER related_id PK,FK 
    }

    relation_spans_networkProviders {
        INTEGER base_id PK,FK 
        INTEGER related_id PK,FK 
    }

    spans {
        INTEGER end FK 
        INTEGER id PK 
        INTEGER network_id FK 
        INTEGER start FK 
    }

    contracts }o--|| networks : "network_id"
    relation_contracts_relatedPhases }o--|| contracts : "base_id"
    nodes }o--|| networks : "network_id"
    organisations }o--|| networks : "network_id"
    phases }o--|| networks : "network_id"
    spans }o--|| networks : "network_id"
    relation_nodes_networkProviders }o--|| nodes : "base_id"
    spans }o--|| nodes : "end"
    spans }o--|| nodes : "start"
    relation_nodes_networkProviders }o--|| organisations : "related_id"
    relation_spans_networkProviders }o--|| organisations : "related_id"
    relation_contracts_relatedPhases }o--|| phases : "related_id"
    relation_spans_networkProviders }o--|| spans : "base_id"

    classDef feature fill:#f3ffa6ff,stroke:#bbd034
    classDef attribute fill:#cec7ffff,stroke:#110e27
    classDef mapping fill:#efefefff,stroke:#434343ff

    class nodes,spans feature
    class networks,organisations,phases,contracts attribute
    class relation_contracts_relatedPhases,relation_spans_networkProviders,relation_nodes_networkProviders mapping
    direction BT
