#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Open Data Services sphinx base documentation build configuration file,
# created by sphinx-quickstart on Wed Nov  2 14:17:45 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import csv
import json
import os
import shutil
import sqlite3

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_nb',
    'sphinxcontrib.opencontracting',
    'sphinxcontrib.opendataservices',
    'sphinxcontrib.jsonschema',
    'sphinx_design',
    'sphinxcontrib.mermaid',
    'crate.sphinx.csv',
    'sphinxcontrib.sqltable',
    'sphinx.ext.imgconverter'
]

#MyST extenions
myst_enable_extensions = [
    "deflist",
    "colon_fence"
]

# MyST heading anchors
myst_heading_anchors = 5

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']

source_suffix = ['.rst', '.md']

# The encoding of source files.
#
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Open Fibre Data Standard'
copyright = '2025, Open Fibre Data Standard'
author = 'Open Fibre Data Standard'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.4'
# The full version, including alpha/beta/rc tags.
release = '0.4.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#
# today = ''
#
# Else, today_fmt is used as the format for a strftime call.
#
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', '_readthedocs', 'Thumbs.db', '.DS_Store','_static/docson']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# on_rtd is whether we are on readthedocs.org, this line of code grabbed from docs.readthedocs.org
import os
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

html_theme = 'sphinx_nefertiti'
    
# otherwise, readthedocs.org uses their theme by default, so no need to specify it

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "logo": "ofds-logo.svg",
    "logo_location": "header",
    "sans_serif_font": "Helvetica",
    "documentation_font": "Helvetica",
    "style": "blue",
    "header_links": [
        {
            "text": "Documentation",
            "link": "index",
        },
        {
            "text": "CoVE",
            "link": "https://ofds.cove.opendataservices.coop/",
            "target": "_blank"
        },
        {
            "text": "ofds.info",
            "link": "https://ofds.info/",
            "target": "_blank"
        },
    ],
    "repository_url": "https://github.com/Open-Telecoms-Data/open-fibre-data-standard",
    "repository_name": "OFDS",
    "project_short": "OFDS",
    "show_powered_by": False
}

html_style = ["custom.css"]

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
#
# html_title = 'Open Data Services Sphinx Base'

# A shorter title for the navigation bar.  Default is the same as html_title.
#
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#
# html_logo = None

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static', '../schema']

html_css_files = ['renderjson.css', 'jsonschema.css']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
html_extra_path = ["../examples/geopackage/network.gpkg"]

# If not None, a 'Last updated on:' timestamp is inserted at every page
# bottom, using the given strftime format.
# The empty string is equivalent to '%b %d, %Y'.
#
# html_last_updated_fmt = None

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# html_additional_pages = {}

# If false, no module index is generated.
#
# html_domain_indices = True

# If false, no index is generated.
#
# html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# html_split_index = False

# If true, links to the reST sources are added to the pages.
#
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr', 'zh'
#
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
#
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'sphinxdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
     # The paper size ('letterpaper' or 'a4paper').
     #
     # 'papersize': 'letterpaper',

     # The font size ('10pt', '11pt' or '12pt').
     #
     # 'pointsize': '10pt',

     # Additional stuff for the LaTeX preamble.
     'preamble': r'\DeclareUnicodeCharacter{2009}{\,}',

     # Latex figure (float) alignment
     #
     # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# latex_documents = [
#     (master_doc, 'sphinx.tex', 'Open Data Services Sphinx Base',
#      'Open Data Services', 'manual'),
# ]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#
# latex_use_parts = False

# If true, show page references after internal links.
#
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
#
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
#
# latex_appendices = []

# It false, will not define \strong, \code, 	itleref, \crossref ... but only
# \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
# packages.
#
# latex_keep_old_macro_names = True

# If false, no module index is generated.
#
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
# man_pages = [
#     (master_doc, 'sphinx', 'Open Data Services Sphinx Base',
#      [author], 1)
# ]

# If true, show URL addresses after external links.
#
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
# texinfo_documents = [
#     (master_doc, 'sphinx', 'Open Data Services Sphinx Base',
#      author, 'sphinx', 'One line description of project.',
#      'Miscellaneous'),
# ]

# Documents to append as an appendix to all manuals.
#
# texinfo_appendices = []

# If false, no module index is generated.
#
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# texinfo_no_detailmenu = False


locale_dirs = ['locale/']   # path is example but recommended.
gettext_compact = False     # optional.

# -- Options for linkcheck builder ---------------------------------------------

linkcheck_ignore = [
    'https://linux.die.net/man/3/libuuid',  # 403 Client Error: Forbidden for url
]

def replace_substring_in_json(file_path, search_substring, replace_string):
    # Read the JSON file
    with open(file_path, 'r') as file:
        data = json.load(file)

    # Recursively search and replace the substring in the JSON data
    _replace_substring_in_json(data, search_substring, replace_string)

    # Write the modified JSON data back to the same file
    with open(file_path, 'w') as file:
        json.dump(data, file, indent=4)


def _replace_substring_in_json(data, search_substring, replace_string):
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, str):
                data[key] = value.replace(search_substring, replace_string)
            else:
                _replace_substring_in_json(value, search_substring, replace_string)
    elif isinstance(data, list):
        for i, item in enumerate(data):
            if isinstance(item, str):
                data[i] = item.replace(search_substring, replace_string)
            else:
                _replace_substring_in_json(item, search_substring, replace_string)


def replace_placeholder_in_gpkg(file_path, search_substring, replace_string):
    # Replace the placeholder in the gpkg_data_columns description column
    connection = sqlite3.connect(file_path)
    try:
        connection.execute(
            "UPDATE gpkg_data_columns SET description = REPLACE(description, ?, ?) WHERE description LIKE ?",
            (search_substring, replace_string, f"%{search_substring}%"),
        )
        connection.commit()
    finally:
        connection.close()


def get_table_metadata(cursor, table_name):
    """
    Retrieves and combines structural and GeoPackage-specific metadata for a single table.
    """
    column_metadata = {}
    foreign_keys = {}

    # 1. Get Structural Metadata (Name, Type, Not Null, Auto Increment)
    # PRAGMA table_info(table_name) returns: cid, name, type, notnull, dflt_value, pk
    try:
        cursor.execute(f"PRAGMA table_info('{table_name}');")
        table_info = cursor.fetchall()
        for col in table_info:
            cid, name, col_type, notnull, dflt_value, pk = col
            column_metadata[name] = {
                'Name': name,
                'Type': col_type,
                'Constraints': [],
                'Title': None,
                'Description': None
            }
            if pk:
              column_metadata[name]['Constraints'].append('PK')
            if notnull:
              column_metadata[name]['Constraints'].append('Not Null')
    except sqlite3.Error as e:
        print(f"Error querying table_info for {table_name}: {e}")
        return []

    # 2. Get Foreign Key Metadata (Reference Table, Reference Column)
    # PRAGMA foreign_key_list(table_name) returns: id, seq, table, from, to, on_update, on_delete, match
    try:
        cursor.execute(f"PRAGMA foreign_key_list('{table_name}');")
        fk_list = cursor.fetchall()
        # The column names for the FK list are: id, seq, table, from, to, on_update, on_delete, match
        fk_names = ["id", "seq", "table", "from", "to", "on_update", "on_delete", "match"]

        for fk in fk_list:
            fk_data = dict(zip(fk_names, fk))
            col_name = fk_data['from']
            if col_name in column_metadata:
                column_metadata[col_name]['Constraints'].append('FK')
                foreign_keys[col_name] = {
                   'Column': col_name,
                   'References':f'FK(`{fk_data["table"]}`.`{fk_data["to"]}`)'
                }
    except sqlite3.Error as e:
        print(f"Error querying foreign_key_list for {table_name}: {e}")

    # 3. Get GeoPackage Metadata (Title annd Description)
    # SELECT column_name, title, description FROM gpkg_data_columns
    try:
        query = f"""
        SELECT column_name, title, description
        FROM gpkg_data_columns
        WHERE table_name = '{table_name}';
        """
        cursor.execute(query)
        gpkg_metadata = cursor.fetchall()
        for col_name, title, description in gpkg_metadata:
            if col_name in column_metadata:
                column_metadata[col_name]['Title'] = title
                column_metadata[col_name]['Description'] = description

    except sqlite3.Error as e:
        print(f"Error querying gpkg_data_columns for {table_name}: {e}")
        # Note: If gpkg_data_columns is missing or the table is not registered, Title/Description will be NULL.

    for metadata in column_metadata.values():
        metadata['Constraints'] = ", ".join(metadata['Constraints'])

    # Convert dictionary values to a list of structured dictionaries for CSV
    return list(column_metadata.values()), list(foreign_keys.values())


def export_metadata_to_csv(gpkg_path, output_dir):
    """
    Main function to connect to the GeoPackage and manage the export process.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    print(f"Connecting to GeoPackage: {gpkg_path}")

    codelist_tables = []
    mapping_tables = []

    try:
        conn = sqlite3.connect(gpkg_path)
        cursor = conn.cursor()

        # 1. Identify tables (data_type 'features' or 'attributes') from gpkg_contents
        cursor.execute("SELECT table_name FROM gpkg_contents WHERE data_type IN ('features', 'attributes');")
        table_names = [row[0] for row in cursor.fetchall()]

        if not table_names:
            print("No feature or attribute tables found in gpkg_contents.")
            return

        print(f"Found {len(table_names)} tables to process: {', '.join(table_names)}")

        # 2. Process each table
        for table_name in table_names:

            metadata_rows, foreign_keys = get_table_metadata(cursor, table_name)

            if not metadata_rows:
                print(f"Skipping empty or error table: {table_name}")
                continue

            if table_name.startswith("codelist"):
                codelist_name = table_name.split("_")[-1]
                codelist_tables.append({
                    "Table": f"`{table_name}`",
                    "Codelist": f"[{codelist_name}](../../codelists.md#{codelist_name.lower()})"
                })
            elif table_name.startswith("relation"):
                mapping_tables.append({
                   "Table": f"`{table_name}`",
                   "base_id FK": foreign_keys[1]['References'].removeprefix("FK(").removesuffix(")"),
                   "related_id FK": foreign_keys[0]['References'].removeprefix("FK(").removesuffix(")")
                })
            else:
                # 3. Write table definition and foreign keys to CSV file
                output_file = os.path.join(output_dir, f"{table_name}.csv")
                with open(output_file, 'w', encoding='utf-8') as csvfile:
                    writer = csv.DictWriter(csvfile, fieldnames=['Name', 'Type', 'Constraints', 'Title', 'Description'], lineterminator='\n')
                    writer.writeheader()
                    writer.writerows(metadata_rows)

                output_file = os.path.join(output_dir, f"{table_name}_fks.csv")
                with open(output_file, 'w', encoding='utf-8') as csvfile:
                    writer = csv.DictWriter(csvfile, fieldnames=['Column', 'References'], lineterminator='\n')
                    writer.writeheader()
                    writer.writerows(foreign_keys)

                print(f"Successfully exported metadata for '{table_name}' to '{output_file}'")

        # 4. Write list of codelist tables and mapping tables to CSV file
        output_file = os.path.join(output_dir, "codelist_tables.csv")
        with open(output_file, 'w', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=["Table", "Codelist"], lineterminator='\n')
            writer.writerows(codelist_tables)

        output_file = os.path.join(output_dir, "mapping_tables.csv")
        with open(output_file, 'w', encoding='utf-8') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=["Table", "base_id FK", "related_id FK"], lineterminator='\n')
            writer.writerows(mapping_tables)

        conn.close()
        print("\nProcessing complete.")

    except sqlite3.Error as e:
        print(f"An SQLite error occurred: {e}")


def setup(app):
    # Connect handlers to events
    app.connect('env-before-read-docs', env_before_read_docs)


# Base URL that `make autobuild` (sphinx-autobuild, no --host/--port) serves docs on locally
LOCAL_DOCS_BASE_URL = 'http://127.0.0.1:8000/'


def env_before_read_docs(app, env, docnames):
    # Get the Sphinx output directory
    outdir = app.outdir
    print(f"Output directory: {outdir}")
    rtd_version = os.getenv('READTHEDOCS_VERSION')

    # Copy schema to output directory
    target_path = os.path.join(outdir, 'network-schema.json')
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    shutil.copyfile('../schema/data_formats/json/network-schema.json', target_path)

    if rtd_version is not None:
        # Replace {{version}} placeholders
        replace_substring_in_json(target_path, '{{version}}', rtd_version)
    else:
        # Point links at the local docs server instead of leaving a broken {{version}} placeholder
        replace_substring_in_json(target_path, 'https://standard.ofds.info/en/{{version}}/', LOCAL_DOCS_BASE_URL)

    # Copy GeoPackage template to output directory
    gpkg_target_path = os.path.join(outdir, 'network-schema.gpkg')
    os.makedirs(os.path.dirname(gpkg_target_path), exist_ok=True)
    shutil.copyfile('../schema/data_formats/geopackage/network-schema.gpkg', gpkg_target_path)

    if rtd_version is not None:
        # Replace {{version}} placeholders
        replace_placeholder_in_gpkg(gpkg_target_path, '{{version}}', rtd_version)
    else:
        # Point links at the local docs server instead of leaving a broken {{version}} placeholder
        replace_placeholder_in_gpkg(gpkg_target_path, 'https://standard.ofds.info/en/{{version}}/', LOCAL_DOCS_BASE_URL)

    # Generate GeoPackage table definition CSV files from the processed GeoPackage template
    export_metadata_to_csv(gpkg_target_path, os.path.join(outdir, 'table_definitions'))

    # Copy other schema and codelist files to output directory
    shutil.copyfile('../schema/data_formats/json/network-package-schema.json', os.path.join(outdir, 'network-package-schema.json'))
    shutil.copytree('../schema/codelists', os.path.join(outdir, 'codelists'), dirs_exist_ok=True)
