---
config:
  layout: elk
---
erDiagram
    Network {
    }
    
    Contract {
    }

    Node {
    }

    Organisation {
    }

    Phase {
    }

    Span {
    }

    Network ||--o{ Node : "Consists of"
    Network ||--o{ Span : "Consists of"
    Network ||--o{ Phase : "Deployed in"
    Node }o--|| Organisation : "Transmission medium owned by"
    Node }o--|| Organisation : "Supporting infrastructure owned by"
    Node }o--|| Organisation : "Active infrastructure operated by"
    Node }o--|| Phase : "Deployed in"
    Span }o--|| Node : "Starts at"
    Span }o--|| Node : "Ends at"
    Span }o--|| Organisation : "Transmission medium owned by"
    Span }o--|| Organisation : "Supporting infrastructure owned by"
    Span }o--|| Organisation : "Active infrastructure operated by"    
    Span }o--|| Organisation : "Installed by"
    Span }o--|| Phase : "Deployed in"
    Contract }o--|| Phase: "Agreement to develop"
    Phase }o--|| Organisation: "Financed by"

    classDef spatial fill:#f3ffa6ff,stroke:#bbd034
    classDef non-spatial fill:#cec7ffff,stroke:#110e27

    class Node,Span spatial
    class Network,Organisation,Phase,Contract non-spatial
    direction LR
